@startuml
class Setor {
    - String codigo
    - String nome
    - int qtdMaxFunc
    - int qtdFunc
    --
    + Setor(String codigo, String nome, int qtdMaxFunc)
    + boolean temVaga()
    + void incrementaFunc()
    + void decrementaFunc()
    + String getCodigo()
    + void setCodigo(String codigo)
    + String getNome()
    + void setNome(String nome)
    + int getQtdMaxFunc()
    + void setQtdMaxFunc(int qtdMaxFunc)
    + int getQtdFunc()
}
@enduml