@startuml
class Triangle {
  +float a
  +float b
  +float c
  +area() : float
}

class Program {
  +run() : void
}

class Main {
  +main() : void
}

Main -> Program : uses
Program -> Triangle : uses

@enduml