@startuml
class Main {
    + main(args: String[]): void
}

class Retangulo {
    - base: double
    - altura: double
    + Retangulo(base: double, altura: double)
    + calcularArea(): double
    + compararArea(outroRetangulo: Retangulo): String
}

Main --> Retangulo : uses

@enduml